INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (6, 'Zaandam', null, 8, '1506EM', 'Wijnkanspad');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (15, 'Wieringerwerf', null, 5, '1771PJ', 'Wanmolen');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (7, 'Heemskerk', null, 2, '1967EC', 'Terschelling');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (8, 'Nieuw-Vennep', null, 65, '2151AE', 'Jonkheer van de Pollstraat');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (9, 'Utrecht', null, 27, '3564KL', 'Houstondreef');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (5, 'Putten', null, 11, '3882VA', 'Picardstraat');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (17, 'Brouwershaven', null, 18, '4318AN', 'Poortdijkstraat');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (16, 'Goes', null, 34, '4461NL', 'Kamperfoeliestraat');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (1, 'Zutphen', null, 47, '7207PK', 'Goethesingel');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (10, 'Apeldoorn', null, 214, '7335EH', 'Arnhemseweg');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (11, 'Deventer', null, 20, '7415AM', 'Ceintuurbaan');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (12, 'Hoogeveen', null, 8, '7901HN', 'De Genestetlaan');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (13, 'Meppel', null, 1, '7944GL', 'Gerard Ter Borchstraat');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (4, 'Biddinghuizen', null, 17, '8256AT', 'Weidehof');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (3, 'Nagele', null, 2, '8308AJ', 'Karwijhof');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (14, 'Marknesse', null, 7, '8316BM', 'Oostervoor');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (2, 'Steenwijk', null, 15, '8331JX', 'Neerwoldstraat');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (19, 'Zuidbroek', null, 1, '9636HA', 'Overburen');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (18, 'Winschoten', null, 51, '9673AB', 'Garst');
INSERT INTO vintageforlife.address (id, city, extension, house_number, postcode, street) VALUES (20, 'Grijpskerk', null, 1, '9843ED', 'Murlinckstraat');
